#!/usr/local/bin/python3

import requests
import json
import sys

api_key = "REPLACE_WITH_YOUR_PUSHOVER_API_KEY"
user_key = sys.argv[1]
message = sys.stdin.read()
priority = 2
device = "iPad"
params = {"token": api_key, "user": user_key, "message": message, "priority": priority, "retry": 30, "expire": 300, "sound": "bugle" }

payload = requests.post("https://api.pushover.net/1/messages.json", params).json()

print("payload: ");
print("----");
print(payload);
print("----");
